name: base
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - anaconda-anon-usage=0.4.4
  - archspec=0.2.3
  - blas=1.0
  - blosc=1.21.6
  - boltons=23.0.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.32.3
  - ca-certificates=2024.7.2
  - cairo=1.18.0
  - cdo=2.4.1
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - conda=24.5.0
  - conda-content-trust=0.2.0
  - conda-libmamba-solver=24.1.0
  - conda-package-handling=2.3.0
  - conda-package-streaming=0.10.0
  - cryptography=42.0.5
  - distro=1.9.0
  - eccodes=2.36.0
  - expat=2.6.2
  - fftw=3.3.10
  - findlibs=0.0.5
  - fmt=9.1.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-anaconda=1
  - fonts-conda-ecosystem=1
  - freeglut=3.4.0
  - freetype=2.12.1
  - fribidi=1.0.10
  - frozendict=2.4.2
  - graphite2=1.3.14
  - harfbuzz=9.0.0
  - hdf4=4.2.15
  - hdf5=1.14.3
  - icu=75.1
  - idna=3.7
  - jasper=4.2.4
  - jsonpatch=1.33
  - jsonpointer=2.1
  - keyutils=1.6.1
  - krb5=1.21.3
  - ld_impl_linux-64=2.38
  - lerc=4.0.0
  - libaec=1.1.3
  - libarchive=3.6.2
  - libcurl=8.9.0
  - libdeflate=1.20
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.6.2
  - libffi=3.4.4
  - libgcc-ng=14.1.0
  - libgfortran-ng=14.1.0
  - libgfortran5=14.1.0
  - libglib=2.80.3
  - libglu=9.0.0
  - libgomp=14.1.0
  - libiconv=1.17
  - libjpeg-turbo=3.0.3
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnetcdf=4.9.2
  - libnghttp2=1.58.0
  - libnsl=2.0.1
  - libopenblas=0.3.21
  - libpng=1.6.43
  - libsolv=0.7.30
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libstdcxx-ng=14.1.0
  - libtiff=4.6.0
  - libudunits2=2.2.28
  - libuuid=2.38.1
  - libwebp-base=1.3.2
  - libxcb=1.16
  - libxcrypt=4.4.36
  - libxml2=2.12.7
  - libzip=1.10.1
  - libzlib=1.3.1
  - lz4-c=1.9.4
  - lzo=2.10
  - magics=4.15.4
  - magics-python=1.5.8
  - menuinst=2.1.1
  - ncurses=6.4
  - numpy=1.26.4
  - numpy-base=1.26.4
  - openssl=3.3.1
  - packaging=23.2
  - pango=1.54.0
  - pcre2=10.44
  - pip=24.0
  - pixman=0.43.2
  - platformdirs=3.10.0
  - pluggy=1.0.0
  - proj=9.4.1
  - pthread-stubs=0.3
  - pybind11-abi=5
  - pycosat=0.6.6
  - pycparser=2.21
  - pysocks=1.7.1
  - python=3.12.2
  - readline=8.2
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.2
  - ruamel.yaml=0.17.21
  - setuptools=69.5.1
  - simplejson=3.17.6
  - snappy=1.2.1
  - sqlite=3.31.1
  - tk=8.6.13
  - tqdm=4.66.4
  - truststore=0.8.0
  - tzdata=2024a
  - udunits2=2.2.28
  - urllib3=2.2.2
  - wheel=0.43.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.1
  - xorg-libsm=1.2.4
  - xorg-libx11=1.8.9
  - xorg-libxau=1.0.11
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.11
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.4.6
  - yaml-cpp=0.8.0
  - zlib=1.3.1
  - zstandard=0.19.0
  - zstd=1.5.6
  - pip:
      - humanize==4.12.1
      - wget==3.2
      - zenodo-get==1.6.1
